version: '3.6'

services:
    www:
        build: .
        restart: always
        container_name: www
        ports:
            - 8000:80
        volumes:
            - . :/var/www/html
        networks: 
            - production-network
        depends_on:
            - db
    db:
        image: postgis/postgis
        ports:
        - 5432:5432
        container_name: db
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: forestcode
            POSTGRES_USER: postgres
        volumes:
            - db_data:/var/lib/postgresql/data 
        networks: 
            - production-network
    db_pgadmin:
        image: dpage/pgadmin4
        container_name: db_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: engsoaresfilho@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - 5050:8080
        networks: 
            - production-network
        depends_on:
            - db
volumes:
    db_data:
    pgadmin:
networks:
    production-network: 
        driver: bridge

